apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend-appset
spec:
  generators:
    - git:
        repoURL: https://git.harness.io/IFG41DWvSnaRLOVNB2uesg/att624org/cassieatt6240/harnessrepo.git
        revision: attworkshop
        files:
        - path: "gitops-workshop/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{environment))-frontend'
      labels:
        harness.io/envRef: '{{environment}}'
        harness.io/serviceRef: '{{harness_service}}'
        harness.io/buildRef: '{{image_tag}}'
    spec:
      project: a6a728ad
      source:
        repoURL: https://git.harness.io/IFG41DWvSnaRLOVNB2uesg/att624org/cassieatt6240/harnessrepo.git
        targetRevision: attworkshop
        path: "gitops-workshop/kustomize/frontend"
        kustomize:
          images:
          - docker.io/cassiesouza/workshop:{{image_tag}}
      destination:
        server: '{{server_address}}'
        namespace: '{{environment}}-frontend'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
