apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: frontend-regcred
    harness.io/skip-versioning: "true"
data:
    .dockerconfigjson: ENC[AES256_GCM,data:g+j51JMtifYfYLyi+23lwG+0t72PRsxpKu4WMdOR6rYsRR/Ci9bpnU9hqUf6R/HH78NDh/QT/JdQAcTbDJf7+B/NJmBwpVkQD/D/X8DZGVXrcZcgyHQrSuInOx9264IHaA2kX6knIR0sE8li/wf8X4jSceeqioZvEe7Dy9nbDK2y9WDle93HxPDHRNyJ3lXeevMDZyQGMTry/6U+3GjojK1y9y/CC2ZaRnlh7Yqq/EcbtP8JZGzWFIjdC0wCElmAecGa+Gvd7NTpvBVz1E4a3VU4LkS7AMHiMU3zMqYztcvg0nJQNbBreuFZWjYc/Li/aq9291GPmBFzPY1tZONU9+dw1twNSnwQ1lnXmfH9U5Nyf7rIaWibrVvv1vKLCUy53Ya6ur0na0Ykq0UDov7MmNSrFqW0Z6qdv4G/TVuI7eVM2mCqhsu2+DM2mBUhBdOQtoni6/UCfNfK2V7s,iv:iZjjG+SqocmHdfBy3Zo2X8bld52sz3QUdcQb9tExSmU=,tag:lCa8B8HiDEQhnVh5oGhitg==,type:str]
sops:
    age:
        - recipient: age1x84e8j07r3gv0rjvwa0pzcmm3mhtt8vrsjlppyrww3wffmfq05jsjvpff3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVWV2amtnaEVzN0tLMktX
            eW9xNE1xOXptUmI0aUdEMjVBdURVSFhDZ3dNCllqeXNqaVZvRlBlSGJ6TVVRL0p2
            MEtYMVlDY2JKTXhlY2VGaXVLNmtvM2sKLS0tIEkvT25CaEJXNWRYUHB5bm1yd3Rp
            Ty9LbEh5ZGVMdVFMRm5qRU56VHJSSXcKInVsEgJcpjhR1B+nNhf20al4mTcchBXK
            GYkqmfPaZECBGJgHi6oI/qXCMuRi3AdnGyu+QcCwLFFn6HS57qi40w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T07:11:11Z"
    mac: ENC[AES256_GCM,data:H9pSexJu63K0TU8ia2PHpYAgiyO2O8kmjqNnYRPcjSIJC0Ts6a1hj94cVz13JCxogMBj/lDO1N2uMtkn4Zgu8yq//68/yyQ4CoGAeG5BJJUgaRCQUN2+tki6vQ0uN8URfrPpWM4IXywFTDDX8zk1IPpoWMg+JGTKIFfGnilbgjc=,iv:XW0j39CWkAa1enRX4Yai4tUpGdhWTsCqh2WEE+3Qp0U=,tag:p22umAsDy1lHreaHnDn+Nw==,type:str]
    encrypted_regex: ^(.dockerconfigjson)$
    version: 3.11.0
